server:
  port: 4000

spring:
  cloud:
    gateway:
      routes:
        - id: map-rendering-service
          uri: http://map-rendering-service:6000
          predicates:
            - Path=/map-rendering/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
