spring:
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESDB_SERVER_NAME}:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DB_NAME}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_USER_PASSWORD}

server:
  port: ${MAP_RENDERING_LOCAL_PORT}
  servlet:
    context-path: /map-rendering/objects
  error:
    include-message: always

cors:
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
