spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESDB_SERVER_NAME}:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DB_NAME}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_USER_PASSWORD}
  r2dbc:
    url: r2dbc:postgresql://${POSTGRESDB_SERVER_NAME}:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DB_NAME}
    username: ${POSTGRESDB_USER}
    password: ${POSTGRESDB_USER_PASSWORD}
  flyway:
    enabled: true
    url: jdbc:postgresql://${POSTGRESDB_SERVER_NAME}:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DB_NAME}
    baseline-on-migrate: true

server:
  port: ${MAP_RENDERING_LOCAL_PORT}
  servlet:
    context-path: /map-rendering/objects

cors:
  allowed-origins: "http://your_frontend_url"
  allowed-methods: "GET,POST,PUT,DELETE"
  allowed-headers: "*"
  allow-credentials: true
  max-age: 3600
